### ISSUE TITLE
セッション部屋の情報を持たせる

### ISSUE THREAD

**Issue by b1a9id** [jjug-ccc/cfp#17]
タイムテーブルを表示するときのキーにするため

**Comment by making** [comment]
`Submission` エンティティに`room_id`を持つのではなく、 `Room` has `Submission`な関係にしてほしい

**Comment by b1a9id** [comment]
修正します！

**Comment by b1a9id** [comment]
まだ全く触ってないissueだから修正ではなかったですw
取り掛かるときはそういう方針でやります

**Comment by making** [comment]
w

**Comment by b1a9id** [comment]
不要なのでcloseします
