### ISSUE TITLE
既存のConference情報にアクセスできない

### ISSUE THREAD

**Issue by making** [jjug-ccc/cfp#18]
https://twitter.com/yusuke/status/960311058039582720

多分 #16 のデグレ

**Comment by making** [comment]
@b1a9id 
https://jjug-cfp.cfapps.io/v1/conferences/00000000-0000-0000-0000-000020171118/submissions
APIは動くけど、
http://www.java-users.jp/ccc2017fall/
が旧APIフォーマットみてるので、js側でエラーになっているっぽい。

スピーカー複数版のフォーマットを`/v2/conferences`にして、`/v1/conferences`と共存させるか、
過去をリセットして`/v1`のままjs側を直すか

**Comment by b1a9id** [comment]
@making 昨日の朝にjsを修正して更新しました。ブラウザのキャッシュを削除すれば、見れる状態ではあります...

**Comment by making** [comment]
👍
APIバージョン問題は見なかったことに。

**Comment by b1a9id** [comment]
@making 確認ありがとうございます！サイトの方はなんとかします！
