### ISSUE TITLE
スピーカー情報のみ取得するAPI実装

### ISSUE THREAD

**Issue by b1a9id** [jjug-ccc/cfp#34]
webサイト掲載のために、選考通過したセッションのスピーカーを取得する。

**Comment by making** [comment]
https://github.com/jjug-ccc/cfp/blob/master/src/main/java/jjug/submission/SubmissionRestController.java#L37-L44

一応、このAPIはAcceptedなものだけ返している

**Comment by b1a9id** [comment]
書き方が悪かったです。
スピーカーのみの一覧を表示するために、重複を取り除いたスピーカーの一覧がほしいです。（複数セッション話される方もいるので）
上のAPIでも実現は可能なので優先度は低めで考えてます。

**Comment by making** [comment]
👍

**Comment by b1a9id** [comment]
不要なのでcloseします
