### ISSUE TITLE
CFPが登録できないことがある

### ISSUE THREAD

**Issue by mike-neck** [jjug-ccc/cfp#37]
What Happens
===

Cfp作成方法にある案内通りにCfpを作成・応募しても登録できないことがある

1. `conferences/{confId}/submissions` ページで Submit CFP ボタンをクリックする
1. `https://jjug-cfp.cfapps.io/` が表示される
1. 作成したCfpが応募中のCfp一覧に表示されない
1. 受け付けた旨のメールも届かない

What's Expected
===

* `https://jjug-cfp.cfapps.io/` に作成したCfpが応募中のCfp一覧に表示される。
* Cfpを受け付けた旨のメールが届く

How to reproduce
===

再現条件は不明

**Comment by mike-neck** [comment]
タイトルのみで後は「T.B.D.」で出したところ、登録されたみたいでした。

ただ、記入する側の観点で言うと、セッションが切れているかどうかわからないので、セッションが切れる目安の時刻が表示されていると、こちらも(一度テキストファイルに対比しておくなどの)対応ができるように思いました

**Comment by making** [comment]
セッションタイムアウトが原因かわかりませんでしたが、
セッションタイムアウト周りの考慮を #38 #39 に上げました。

**Comment by mike-neck** [comment]
ありがとうございます！

**Comment by megascus** [comment]
submit押したときにローカルストレージに保存しておいて、うまくいってなかったら次はそのローカルストレージの内容を引き継いで表示するぐらいしてもいいのかもねぇ。

**Comment by making** [comment]
pull req欲しい
