### ISSUE TITLE
CfP募集サイトの募集要項を募集が終了しても見えるようにする

### ISSUE THREAD

**Issue by megascus** [jjug-ccc/cfp#64]
現在は募集終了後は何も確認が出来なくなってしまうが、
募集要項に何が記載されていたかは募集終了後も見えたほうが良い。
費用の確認等が必要になる場合があるし、次回募集までのユーザー向けの参考にもなる。

-----

making:tm: 2:12 PM
https://github.com/jjug-ccc/cfp/blob/master/src/main/java/jjug/submission/SubmissionController.java#L81-L88
ここのチェックを変える感じか
https://github.com/jjug-ccc/cfp/blob/master/src/main/java/jjug/submission/SubmissionController.java#L85
このチェックなくてもいい気がしてきた
フォーム側でチェックしていれば。

megascus 2:46 PM
フォーム側でチェックしてればよいですね。フォームへのリンク消せるのが一番いいと思うけど。

making:tm: 2:49 PM
概要に書かれているフォームのリンク以外はテンプレートの方で消せる
boot2系へのバージョンアップもやりたい…

**Comment by making** [comment]
thanks
