### ISSUE TITLE
スピーカー応募時に所属が必須になっている

### ISSUE THREAD

**Issue by megascus** [jjug-ccc/cfp#69]
スピーカー応募時に個人での応募も考えられると思うのですが、所属を必須にしてるのって何か理由があるんでしたっけ？
(CCCなんだからどこかのコミュニティの代表として応募してほしいという話？)

https://github.com/jjug-ccc/cfp/blob/master/src/main/java/jjug/submission/SpeakerForm.java#L19-L21
https://github.com/jjug-ccc/cfp/blob/master/src/main/resources/templates/submission/submissionForm.html#L118-L123

**Comment by making** [comment]
所属書いて欲しいからかな。個人の場合は"Indivisual"とか"個人"とか書いてもらえれば。

**Comment by megascus** [comment]
了解です。
何書けばいいのという問い合わせがあったので。
何かしら書いてもらうことを優先させるということでクローズします。
